Repository delta-reporter/delta-core, pull requests merged in 2020-06, with the labels that each got.

#13 Added parameters for test history
  app.py
  data/crud.py
  migrations/versions/d31320fd769e_.py
  models.py
Labels: enhancement, python

#14 Added new table and endpoint to store retries
  Delta Reporter.postman_collection.json
  app.py
  data/crud.py
  migrations/versions/3d6b36b7396b_.py
  models.py
Labels: enhancement, python

#16 Expanding failed tests endpoint
  app.py
  data/crud.py
Labels: enhancement

#15 Media endpoints and media storage for test_history and test_retries
  app.py
  data/crud.py
  migrations/versions/feef539bd698_.py
  models.py
Labels: python
